#!/usr/bin/env python3

import sys
import os
from lazylib.hashedcopyer import HashedCopyer

def main():
    if len(sys.argv) < 4:
        print(f"Copy files from source_dir to dest_dir(s).")
        print(f"The filename at dest_dir will be SHA512 of the file content.")
        print(f"")
        print(f"Skip file copy if")
        print(f"    * File modification time is earlier than time_threshold")
        print(f"    * File already exist in ANY of the dest_dir")
        print(f"")
        print(f"It accept multiple dest_dir. It will be evaluated one-by-one,")
        print(f"skipping any destination more than 95% full.")
        print(f"")
        print(f"Syntax: {sys.argv[0]} source_dir time_threshold dest_dir...")
        sys.exit(1)

    argv_list = sys.argv
    argv_list.pop(0)
    src_dir = argv_list.pop(0)
    threshold_ts = float(argv_list.pop(0))
    dst_dir_list = argv_list

    copyer = HashedCopyer(dst_dir_list)
    for root, dirs, files in os.walk(src_dir):
        for file_name in files:
            copyer.copy(
                    src_file=os.path.join(root, file_name),
                    threshold_ts=threshold_ts, 
                    )

if __name__ == "__main__":
    main()

