#!/usr/bin/env python3

import sys
import os
from lazylib.hashedcopyer import HashedCopyer
from lazylib.consoleprogress import ConsoleProgress

def main():
    if len(sys.argv) < 2:
        print(f"Verify the file content matches the file name.")
        print(f"The filename is expected to be the SHA512 of the content.")
        print(f"")
        print(f"Syntax: {sys.argv[0]} dirs...")
        sys.exit(1)

    con = ConsoleProgress()
    argv_list = sys.argv
    argv_list.pop(0)
    arg_dir_list = argv_list

    file_count = 0
    file_mismatch_count = 0
    byte_count = 0

    for arg_dir in arg_dir_list:
        for walk_root, walk_dirs, walk_files in os.walk(arg_dir):
            for walk_file in walk_files:
                file_pathname = os.path.join(walk_root, walk_file)
                file_basename = os.path.basename(walk_file)
                sha512 = HashedCopyer.generate_file_sha512(file_pathname)
                file_size = os.path.getsize(file_pathname)
                file_count += 1
                byte_count += file_size
                if file_basename != sha512:
                    con.print(f"Mismatch: {file_pathname}")
                    file_mismatch_count += 1
                else:
                    con.update(f"Progress: {byte_count:_} bytes in {file_count:_} files")

    if file_mismatch_count == 0:
        con.print(f"{byte_count:_} bytes in {file_count:_} files verified")
        sys.exit(0)
    else:
        con.print(f"WARNING: {file_count:_} files mismatch")
        sys.exit(1)

if __name__ == "__main__":
    main()

