#!/bin/bash
set -e

if [ "$#" != "1" ]; then
    echo "Syntax error"
    exit 1
fi

if ! [ -b "${1}" ]; then
    echo "${1} is not a block device"
    exit 1
fi

device_basename=$(basename $1)

dd if=/dev/zero of=/dev/${device_basename} bs=1M count=8
dd if=/dev/zero of=/dev/${device_basename} bs=1M seek=$(($(cat /sys/block/${device_basename}/size)/2/1024 - 8)) || :
sync

echo -e "o\nn\np\n1\n\n\nt\n07\np\nw" | fdisk ${1}
sync

