#!/bin/bash

if [ "$#" != "1" ]; then
    echo "Syntax error"
    exit 1
fi

if ! [ -b "$1" ]; then
    echo "$1 is not a block device"
    exit 1
fi

block_device=$1

mkfs.vfat -n ${USER} ${block_device}
sync

